name: Deploy to surge

# on: [push]

on:
    [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'

        - name: Install dependencies
          run: npm ci

        - name: Build web
          run: npm ci

        - name: Install surge
          run: npm install -g surge
        
        - name: Deploy to surge
          run: surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

    